/**
 * INDUSTRIAL DEMO FEEDER LIST GENERATOR
 * Creates an Excel file with realistic power plant data
 * Includes all required fields for IEC 60364 compliance
 */

// This will be converted to Excel format
// Format: JSON rows that will be converted to XLSX

export const IndustrialDemoFeeders = [
  {
    // Feeder 1: 3-phase Motor (Pump) - typical power plant
    'SL #': 1,
    'Load Type': 'Pump',
    'Feeder Description': 'Boiler Feed Pump Motor 1',
    'From Bus': 'MCC-1',
    'To Bus': 'BFP-MOTOR-1',
    'Voltage (V)': 6600,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 500,
    'Power Factor': 0.88,
    'Efficiency (%)': 92.5,
    'Efficiency (decimal)': 0.925,
    'Starting Method': 'SoftStarter',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Air - Ladder tray (touching)',
    'Cable Spacing': 'touching',
    'Length (m)': 150,
    'Ambient Temp (°C)': 40,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 4,
    'Max Short Circuit at Point (kA)': 25,
    'Protection Clearing Time (s)': 0.1
  },
  {
    // Feeder 2: Motor (Fan) - cooling tower
    'SL #': 2,
    'Load Type': 'Fan',
    'Feeder Description': 'Cooling Tower Fan Motor A',
    'From Bus': 'MCC-2',
    'To Bus': 'CT-FAN-A',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 45,
    'Power Factor': 0.85,
    'Efficiency (%)': 90.0,
    'Efficiency (decimal)': 0.90,
    'Starting Method': 'StarDelta',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Air - Conduit (single)',
    'Cable Spacing': 'touching',
    'Length (m)': 85,
    'Ambient Temp (°C)': 45,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 3,
    'Max Short Circuit at Point (kA)': 15,
    'Protection Clearing Time (s)': 0.1
  },
  {
    // Feeder 3: Motor (Compressor) - air system
    'SL #': 3,
    'Load Type': 'Compressor',
    'Feeder Description': 'Air Compressor Motor',
    'From Bus': 'MCC-3',
    'To Bus': 'COMPRESSOR-1',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 22,
    'Power Factor': 0.82,
    'Efficiency (%)': 88.5,
    'Efficiency (decimal)': 0.885,
    'Starting Method': 'VFD',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '4C',
    'Installation Method': 'Buried - In duct',
    'Cable Spacing': 'spaced_400mm',
    'Length (m)': 120,
    'Ambient Temp (°C)': 35,
    'Soil Thermal Resistivity': 1.5,
    'Depth of Laying (cm)': 70,
    'Grouped Loaded Circuits': 2,
    'Max Short Circuit at Point (kA)': 10,
    'Protection Clearing Time (s)': 0.15
  },
  {
    // Feeder 4: Heater - space heating
    'SL #': 4,
    'Load Type': 'Heater',
    'Feeder Description': 'Main Space Heater Panel',
    'From Bus': 'Distribution-Panel-1',
    'To Bus': 'HEATER-MAIN',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 75,
    'Power Factor': 1.0,
    'Efficiency (%)': 99.0,
    'Efficiency (decimal)': 0.99,
    'Starting Method': 'N/A',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Air - Ladder tray (touching)',
    'Cable Spacing': 'touching',
    'Length (m)': 50,
    'Ambient Temp (°C)': 40,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 5,
    'Max Short Circuit at Point (kA)': 20,
    'Protection Clearing Time (s)': 0.1
  },
  {
    // Feeder 5: Transformer - step-down transformer
    'SL #': 5,
    'Load Type': 'Transformer',
    'Feeder Description': '33kV to 6.6kV Step-down Transformer Feeder',
    'From Bus': 'Switch-Yard-33kV',
    'To Bus': 'TransformerTRF-1',
    'Voltage (V)': 33000,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 5000,
    'Power Factor': 0.95,
    'Efficiency (%)': 97.5,
    'Efficiency (decimal)': 0.975,
    'Starting Method': 'N/A',
    'Conductor Material': 'Al',
    'Insulation': 'XLPE',
    'Number of Cores': '3C',
    'Installation Method': 'Air - Ladder tray (spaced 400mm)',
    'Cable Spacing': 'spaced_400mm',
    'Length (m)': 300,
    'Ambient Temp (°C)': 35,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 1,
    'Max Short Circuit at Point (kA)': 50,
    'Protection Clearing Time (s)': 0.2
  },
  {
    // Feeder 6: Feeder to sub-distribution
    'SL #': 6,
    'Load Type': 'Feeder',
    'Feeder Description': 'Main Feeder to Sub-distribution Panel 1',
    'From Bus': 'Main-Distribution',
    'To Bus': 'Sub-Panel-1',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 200,
    'Power Factor': 0.92,
    'Efficiency (%)': 98.5,
    'Efficiency (decimal)': 0.985,
    'Starting Method': 'N/A',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Air - Conduit (multi)',
    'Cable Spacing': 'touching',
    'Length (m)': 75,
    'Ambient Temp (°C)': 40,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 6,
    'Max Short Circuit at Point (kA)': 22,
    'Protection Clearing Time (s)': 0.1
  },
  {
    // Feeder 7: Large Motor - high power
    'SL #': 7,
    'Load Type': 'Pump',
    'Feeder Description': 'Condensate Return Pump Motor',
    'From Bus': 'MCC-4',
    'To Bus': 'COND-PUMP-MOTOR',
    'Voltage (V)': 6600,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 350,
    'Power Factor': 0.87,
    'Efficiency (%)': 91.5,
    'Efficiency (decimal)': 0.915,
    'Starting Method': 'SoftStarter',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Buried - Direct in ground',
    'Cable Spacing': 'touching',
    'Length (m)': 200,
    'Ambient Temp (°C)': 30,
    'Soil Thermal Resistivity': 1.0,
    'Depth of Laying (cm)': 80,
    'Grouped Loaded Circuits': 2,
    'Max Short Circuit at Point (kA)': 28,
    'Protection Clearing Time (s)': 0.12
  },
  {
    // Feeder 8: Medium motor - VFD driven
    'SL #': 8,
    'Load Type': 'Fan',
    'Feeder Description': 'Induced Draft Fan Motor (VFD)',
    'From Bus': 'MCC-5',
    'To Bus': 'ID-FAN-MOTOR',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 55,
    'Power Factor': 0.88,
    'Efficiency (%)': 91.0,
    'Efficiency (decimal)': 0.91,
    'Starting Method': 'VFD',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '4C',
    'Installation Method': 'Air - Ladder tray (touching)',
    'Cable Spacing': 'touching',
    'Length (m)': 110,
    'Ambient Temp (°C)': 42,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 4,
    'Max Short Circuit at Point (kA)': 18,
    'Protection Clearing Time (s)': 0.1
  },
  {
    // Feeder 9: Emergency Lighting
    'SL #': 9,
    'Load Type': 'Heater',
    'Feeder Description': 'Emergency Lighting Panel',
    'From Bus': 'UPS-Output',
    'To Bus': 'EMERG-LIGHT-PANEL',
    'Voltage (V)': 230,
    'Phase': '1Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 5,
    'Power Factor': 0.98,
    'Efficiency (%)': 98.0,
    'Efficiency (decimal)': 0.98,
    'Starting Method': 'N/A',
    'Conductor Material': 'Cu',
    'Insulation': 'PVC',
    'Number of Cores': '2C',
    'Installation Method': 'Air - Conduit (single)',
    'Cable Spacing': 'touching',
    'Length (m)': 40,
    'Ambient Temp (°C)': 38,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 3,
    'Max Short Circuit at Point (kA)': 8,
    'Protection Clearing Time (s)': 0.08
  },
  {
    // Feeder 10: Control Panel
    'SL #': 10,
    'Load Type': 'Feeder',
    'Feeder Description': 'DCS/SCADA Control System Panel',
    'From Bus': 'Control-Supply-Panel',
    'To Bus': 'DCS-PANEL-ROOM',
    'Voltage (V)': 415,
    'Phase': '3Ø',
    'Frequency (Hz)': 50,
    'Rated Power (kW)': 25,
    'Power Factor': 0.95,
    'Efficiency (%)': 97.0,
    'Efficiency (decimal)': 0.97,
    'Starting Method': 'N/A',
    'Conductor Material': 'Cu',
    'Insulation': 'XLPE',
    'Number of Cores': '3C+E',
    'Installation Method': 'Air - Conduit (single)',
    'Cable Spacing': 'touching',
    'Length (m)': 60,
    'Ambient Temp (°C)': 40,
    'Soil Thermal Resistivity': 1.2,
    'Depth of Laying (cm)': 60,
    'Grouped Loaded Circuits': 2,
    'Max Short Circuit at Point (kA)': 15,
    'Protection Clearing Time (s)': 0.1
  }
];

// Export for use in creating Excel
export default IndustrialDemoFeeders;
